//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ileriveritabaniproje1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LİmanYatTekneTakipSistemiEntities : DbContext
    {
        public LİmanYatTekneTakipSistemiEntities()
            : base("name=LİmanYatTekneTakipSistemiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<shipLocation> shipLocations { get; set; }
        public virtual DbSet<ship> ships { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
