//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ileriveritabaniproje1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ship
    {
        public ship()
        {
            this.shipLocations = new HashSet<shipLocation>();
        }
    
        public int id { get; set; }
        public string ShipName { get; set; }
        public string capacity { get; set; }
        public string color { get; set; }
        public string task { get; set; }
        public string type_of_ship { get; set; }
        public string ship_size { get; set; }
    
        public virtual ICollection<shipLocation> shipLocations { get; set; }
    }
}
