//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ileriveritabaniproje1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shipLocation
    {
        public int location_id { get; set; }
        public string locationName { get; set; }
        public System.Data.Entity.Spatial.DbGeography location { get; set; }
        public byte[] image { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<int> ship_id { get; set; }
    
        public virtual ship ship { get; set; }
    }
}
